# Generated by Django 5.0.3 on 2024-08-08 17:10

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=apps.users.models.generate_unique_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
