# Generated by Django 5.0.3 on 2024-11-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gmail_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gmail',
        ),
    ]
