# Generated by Django 5.0.1 on 2024-04-28 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_title', models.CharField(blank=True, max_length=256, null=True)),
                ('second_title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='img/banners/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_title', models.CharField(blank=True, max_length=256, null=True)),
                ('docs', models.FileField(upload_to='docs/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='first_contact',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='second_contact',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
