# Generated by Django 5.0.3 on 2024-10-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_remove_request_additional_materials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
