# Generated by Django 5.0.3 on 2024-10-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_rename_date_created_request_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('catgo', 'Запрос на карго'), ('simple', 'Простая заявка'), ('search', 'Запрос на поиск')], max_length=16),
        ),
    ]
