# Generated by Django 5.0.3 on 2024-10-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_alter_request_additional_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='additional_information',
        ),
    ]
