# Generated by Django 5.0.3 on 2024-10-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_remove_request_additional_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='manager_chice',
            new_name='manager_choice',
        ),
    ]
