# Generated by Django 5.0.3 on 2024-10-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_rename_manager_chice_request_manager_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('cargo', 'Запрос на карго'), ('simple', 'Простая заявка'), ('search', 'Запрос на поиск')], max_length=16),
        ),
    ]
