# Generated by Django 5.0.3 on 2024-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_alter_request_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='manager_choice',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='search_item',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='service_choice',
            field=models.CharField(max_length=255),
        ),
    ]
