# Generated by Django 5.0.3 on 2024-10-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_alter_request_manager_choice_alter_request_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('canceled', 'Отклонен')], default='new', max_length=20),
        ),
    ]
