# Generated by Django 5.0.3 on 2024-10-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('cargo', 'Cargo Request'), ('simple', 'Simple Request'), ('search', 'Search Request')], max_length=16),
        ),
    ]
